### PR TITLE
Run testify from virtualenv

### PR DESCRIPTION
**Pull request by kkellyy**
Not necessarily installed at system-level

### CODE REVIEW

**Comment by asottile** [comment]
Do we actually still use catbox? I was under the impression it never really worked and was deprecated for things like docker --net=none

**Comment by kkellyy** [comment]
Still worth fixing the build of this, but I don't think so.

**Comment by asottile** [comment]
Probably not worth it, I'd just move this repo to YelpArchive and stop building it internally

**Comment by kkellyy** [comment]
Yeah, I agree now. Took me more than 10 minutes, so I give up. Just wanted to stop the fail spam.

**Pull request closed without merging**
